apps/loginreg_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'register$', views.register, name='register'),
    url(r'login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout')
]

apps/wishlist_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^create$', views.create, name='create'),
    url(r'^process$', views.process, name='process'),
    url(r'^dashboard/(?P<item_id>\d+)$', views.dashboard, name='dashboard'),
    url(r'^join/(?P<item_id>\d+)$', views.join, name='join'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^delete/(?P<item_id>\d+)$', views.delete, name='delete'),
    url(r'^remove/(?P<item_id>\d+)$', views.remove, name='remove')
]

wish_list_exam/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.loginreg_app.urls', namespace="login")),
    url(r'^wishlist', include('apps.wishlist_app.urls', namespace="wishlist"))
]

apps/loginreg_app/models.py
from __future__ import unicode_literals
from django.db import models
import bcrypt
from datetime import datetime
import re

name_regex = re.compile("^[a-zA-Z\s]+$")

class UserManager(models.Manager):
    def register(self, input):
        errors = []

        if len(input['name']) < 3:
            errors.append('Name can not be less than 3 characters')

        if not name_regex.match(input['name']):
            errors.append('Name can contain letters only')

        if len(input['username']) < 3:
            errors.append('Username can not be less than 3 characters')

        if input['password'] != input['confirm']:
            errors.append('Passwords do not match. Try again')

        if len(input['password']) < 8:
            errors.append('Password must be at least 8 characters')

        same = Person.objects.filter(username=input['username'])
        if same:
            errors.append('Username is already in use')

        if not input['hire_date']:
            errors.append('Please enter the date hired')
        else:
            date = datetime.strptime(input['hire_date'], "%Y-%m-%d")
            if datetime.today() <= date:
                errors.append('Hire date cannot be after today')

        if len(errors) == 0:
            pwHash = bcrypt.hashpw(input['password'].encode(), bcrypt.gensalt().encode())
            user = Person.objects.create(name=input['name'], username=input['username'], hire_date=input['hire_date'], password=pwHash)
            return (True, user)

        else:
            return (False, errors)

    def login(self, input):
        errors = []
        user = Person.objects.filter(username=input['username'])
        if user.exists():
            InputPw = input['password'].encode()
            HashPw = user[0].password.encode()

            if bcrypt.checkpw(InputPw, HashPw):
                return (True, user[0])
            else:
                errors.append(("Username and password does not exist!"))
        else:
            errors.append(("Username and password does not exist!"))
        return (False, errors)

class Person(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=100)
    hire_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/wishlist_app/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginreg_app.models import Person
from datetime import datetime


class ProductManager(models.Manager):

    def addProduct(self, input, user):
        errors = []

        if len(input['item']) == 0:
            errors.append('Please fill out')

        if len(input['item']) < 4:
            errors.append('Entry must be more than 3 characters')


        if len(errors) == 0:
            date = datetime.now()
            product = Product.objects.create(item=input['item'], user=user, date_added=date)
            product.group.add(user)
            product.save()
            return (True, 'Added to your wish list!')
        else:
            return (False, errors)


    def joinProduct(self, item_id, user):
        item = Product.objects.get(id=item_id)
        item.group.add(user)
        item.save()
        return (True, "Added item to Wishlist!")

class Product(models.Model):
    item = models.CharField(max_length=255)
    date_added = models.DateField()
    user = models.ForeignKey(Person)
    group = models.ManyToManyField(Person, related_name="wishlist")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = ProductManager()

apps/loginreg_app/views.py
from django.shortcuts import render, redirect
from .models import Person
from django.contrib import messages
from django.core.urlresolvers import reverse


def index(request):
    if 'user_id' in request.session:
        return redirect(reverse('wishlist:index'))
    else:
        return render(request, 'loginreg_app/index.html')

def register(request):
    result = Person.objects.register(request.POST)
    if result[0] == True:
        request.session['user_id'] = result[1].id
        messages.success(request, "Hello! You have registered! Now log in.")
        return redirect(reverse('login:index'))
    else:
        for error in result[1]:
            messages.error(request, error)
        return redirect(reverse('login:index'))

def login(request):
    result = Person.objects.login(request.POST)
    if result[0] == True:
        request.session['user_id'] = result[1].id
        return redirect(reverse('wishlist:index'))
    else:
        for error in result[1]:
            messages.error(request, error)
        return redirect(reverse('login:index'))

def logout(request):
    if 'user_id' in request.session:
        del request.session['user_id']
        messages.success(request, "You have been logged out")
        return redirect(reverse('login:index'))

apps/wishlist_app/views.py
from django.shortcuts import render, redirect
from .models import Product
from ..loginreg_app.models import Person
from django.core.urlresolvers import reverse
from django.contrib import messages


def index(request):
    if 'user_id' in request.session:
        user = Person.objects.get(id=request.session['user_id'])
        context = {
            'data': user,
            'items': Product.objects.all().filter(group=user),
            'users': Product.objects.all().exclude(group=user)
        }
        return render(request, 'wishlist_app/index.html', context)
    else:
        return redirect(reverse('login:index'))

def create(request):
    return render(request, 'wishlist_app/create.html')

def process(request):
    if request.method == 'POST':
        user = Person.objects.get(id=request.session['user_id'])
        result = Product.objects.addProduct(request.POST, user)
        if result[0] == True:
            messages.success(request, result[1])
            return redirect(reverse('wishlist:index'))
        else:
            for error in result[1]:
                messages.error(request, error)
            return redirect(reverse('wishlist:create'))

def dashboard(request, item_id):
    item = Product.objects.get(id=item_id)
    context = {
        'items': item,
        'users': item.group.all()
    }
    return render(request, 'wishlist_app/dashboard.html', context)

def join(request, item_id):
    user = Person.objects.get(id=request.session['user_id'])
    result = Product.objects.joinProduct(item_id, user)
    messages.success(request, result[1])
    return redirect(reverse('wishlist:index'))

def delete(request, item_id):
    Product.objects.get(id=item_id).delete()
    messages.success(request, "deleted")
    return redirect(reverse('wishlist:index'))

def remove(request, item_id):
    user = Person.objects.get(id=request.session['user_id'])
    item = Product.objects.get(id=item_id)
    item.group.remove(user)
    messages.success(request, "removed from Wishlist")
    return redirect(reverse('wishlist:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('login:index'))


# Create your views here.

apps/loginreg_app/templates/loginreg_app/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Login and Registration</title>
  </head>
  <body>
    <h2>Hello and Welcome to your Wishlist Page!</h2>
    <div id="wrapper">
      <div class="message">
        {% if messages %}
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        {% endif %}
      </div>

      <div class="register">
        <h1>Register</h1>
        <form class="ui form" action="{% url 'login:register' %}" method="post">
          {% csrf_token %}
          Name: <input type="text" name="name" placeholder="Name">
          Username: <input type="text" name="username" placeholder="Username">
          Password: <input type="password" name="password" placeholder="Password">
          Confirm Password: <input type="password" name="confirm" placeholder="Confirm Password">
          Date: <input type="date" name="hire_date">
          <input type="submit" value="Register">
        </form>
      </div>

      <div class="login">
        <h1>Login</h1>
        <form class="ui form" action="{% url 'login:login' %}" method="post">
          {% csrf_token %}
          Username: <input type="text" name="username" placeholder="Username">
          Password: <input type="password" name="password" placeholder="Password">
          <input type="submit" value="Login">
        </form>
      </div>
    </div>
  </body>
</html>

apps/wishlist_app/templates/wishlist_app/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Create Item</title>
  </head>

  <body>
    <a href="/"><button>Home</button></a>
    <a href="/logout"><button>Log Out</button></a>

    <div>
      <h1>Create a New Wish List Item</h1>
      <form class="ui form" action="{% url 'wishlist:process' %}" method="post">
        {% csrf_token %}
        Item/Product: <input type="text" name="item" placeholder="Item/Product"><br><br>
        <input type="submit" value="Add">
      </form>
      {% if messages %}
          <ul>
          {% for message in messages %}
              <li>{{message}}</li>
          {% endfor %}
          </ul>
      {% endif %}
    </div>
  </body>
</html>

apps/wishlist_app/templates/wishlist_app/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Dashbaord</title>
  </head>
  <body>
    {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{message}}</li>
        {% endfor %}
        </ul>
    {% endif %}
    <a href="/"><button>Home</button></a>
    <a href="/logout"><button>Log Out</button></a>

    <h1>Product: {{items.item}}</h1><br><br>
    <h2>Users who added this item under their wish list</h2>
    {% for others in users %}
    <h3>{{others.name}}</h3>
    {% endfor %}
  </body>
</html>

apps/wishlist_app/templates/wishlist_app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My Wish List</title>
  </head>
  <body>
    <h1>Hello, {{data.name}}!</h1>
    <a href="/logout"><button>Log Out</button></a>
    <a href="{% url 'wishlist:create' %}"><button>Add Item</button></a>

    {% if messages %}
        <ul>
        {% for message in messages %}
            <li>{{message}}</li>
        {% endfor %}
    {% endif %}

    <h3>Your Wish List:</h3>
    <table class="ui celled table">
      <thead>
        <tr>
          <th>Item</th>
          <th>Added By</th>
          <th>Date Added</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td><a href="{% url 'wishlist:dashboard' item.id %}">{{item.item}}</a></td>
          <td>{{item.user.name}}</td>
          <td>{{item.date_added}}</td>
          {% if data == item.user %}
          <td><a href="{% url 'wishlist:delete' item.id %}">Delete</a></td>
          {% else %}
          <td><a href="{% url 'wishlist:remove' item.id %}">Remove from my Wishlist</a></td>
        </tr>
        {% endif %}
        {% endfor %}
      </tbody>
    </table>

    <h3>Other Users' Wish List</h3>
    <table class="ui celled table">
      <thead>
        <tr>
          <th>Item</th>
          <th>Added By</th>
          <th>Date Added</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for user in users %}
        <tr>
          <td><a href="{% url 'wishlist:dashboard' user.id %}">{{user.item}}</a></td>
          <td>{{user.user.name}}</td>
          <td>{{user.date_added}}</td>
          <td><a href="{% url 'wishlist:join' user.id %}">Add to my Wishlist</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>